from typing import Any, Callable

__version__: str
__build_profile__: str

class Runtime:
    _clock: int
    _closed: bool
    _context: bool
    _sigset: list[int]
    _sig_wfd: Any
    _sig_listening: bool
    _ssock_r: Any
    _ssock_w: Any
    _stopping: bool

    def __init__(
        self, threads: int, threads_blocking: int, threads_blocking_timeout: int, context: bool, signals: list[int]
    ): ...
    def _run(self): ...
    def _spawn_coro(self, coro): ...
    def _call_soon(self, callback: Callable[[], object]): ...
    def _call_soon_deferred(self, callback: Callable[[], object]): ...
    def _spawn_blocking(self, f, *args, **kwargs) -> tuple[BlockingTaskCtl, Event, Result]: ...
    def _sig_add(self, sig: int) -> Event: ...
    def _sig_rem(self, sig: int) -> bool: ...

class Waiter:
    def __init__(self, *events: Event): ...
    def checkpoint() -> Waiter: ...
    def abort(self): ...

class Event:
    def __init__(self): ...
    def set(self): ...
    def clear(self): ...
    def is_set(self) -> bool: ...
    def waiter(self, timeout: int | None) -> Waiter: ...

class Result:
    def __init__(self, size: int = 1): ...
    def store(self, value, index: int | None = None): ...
    def fetch(self): ...

class BlockingTaskCtl:
    def abort(self): ...

class CancelledError(BaseException): ...
class RuntimeAlreadyInitializedError(RuntimeError): ...
class RuntimeNotInitializedError(RuntimeError): ...

class ScheduledIO:
    def __init__(self, fd: int): ...
    def _arm_r(self, timeout: int | None = None) -> Waiter | None: ...
    def _arm_w(self, timeout: int | None = None) -> Waiter | None: ...
    def _arm_r_cb(self, cb: Any) -> bool: ...
    def _arm_w_cb(self, cb: Any) -> bool: ...
    def consume_r(self) -> bool: ...
    def consume_w(self) -> bool: ...
    def clear_r(self): ...
    def clear_w(self): ...
    def close(self): ...

def get_runtime() -> Runtime: ...
def set_runtime(runtime: Runtime): ...
