name: test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.14t'
        - '3.15t'

    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ env.UV_PYTHON }}
        uv venv .venv
        uv sync --group build --group test
        uv run --no-sync maturin develop --uv
    - name: Test
      run: |
        source .venv/bin/activate
        make test

  macos:
    runs-on: macos-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - '3.14t'
        - '3.15t'

    env:
      UV_PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: false
    - name: Install
      run: |
        uv python install ${{ env.UV_PYTHON }}
        uv venv .venv
        uv sync --group build --group test
        uv run --no-sync maturin develop --uv --extras=test
    - name: Test
      run: |
        source .venv/bin/activate
        make test

  # windows:
  #   runs-on: windows-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version:
  #       - '3.14t'

  #   env:
  #     UV_PYTHON: ${{ matrix.python-version }}
  #   steps:
  #   - uses: actions/checkout@v7
  #   - uses: astral-sh/setup-uv@v7
  #     with:
  #       enable-cache: false
  #   - name: Install
  #     run: |
  #       uv python install ${{ env.UV_PYTHON }}
  #       uv venv .venv
  #       uv sync --group build --group test
  #       uv run --no-sync maturin develop --uv --extras=test
  #   - name: Test
  #     run: |
  #       uv run --no-sync make test
